[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
webproof = "vKofkBS5rcgK3V8HemwiZZygPQYd4e6GTyUGTvFRB7p"

[programs.localnet]
webproof = "vKofkBS5rcgK3V8HemwiZZygPQYd4e6GTyUGTvFRB7p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/webproof"]

[scripts]
test = "pnpm --filter @webproof/sdk build && pnpm --dir tests/program test"
