[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
webproof = "BU1KznoqTFTHgYpcvgFAS5AqqtqnwrrcjLAczpHwgKMR"

[programs.devnet]
webproof = "BU1KznoqTFTHgYpcvgFAS5AqqtqnwrrcjLAczpHwgKMR"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/webproof"]

[scripts]
test = "pnpm --filter @webproof/sdk build && pnpm --dir tests/program test"
